### ISSUE TITLE
Remove netlify css from admin page

### ISSUE THREAD

**Issue by uyar** [getnikola/nikola-netlify-cms#11]
The admin page (`files/admin/index.html`) includes a stylesheet link to `https://unpkg.com/netlify-cms@latest/dist/cms.css`. That file has the following contents:

```
/**
 * Netlify CMS 2.0 moved from static CSS to CSS-in-JS. Some site builds are configured to look
 * for `cms.css`, and will break when it's missing, so we're putting out this blank file to help.
 * We'll eventually remove it, so please update your build to not require it.
 */
```

**Comment by Kwpolska** [comment]
Could you please make a pull request for this, and also #7/#8/#9/#10?

**Comment by uyar** [comment]
Sure, but do you want them as separate PRs so that you can review them separately, or as a single PR? Creating branches for separate PRs has been a pain for me in the past because the order of applying them would be significant. And especially #8 might benefit from your judgment about which fields to include.
