### ISSUE TITLE
Nikola build failing for Jupyter notebooks due to missing dependencies

### ISSUE THREAD

**Issue by k-allika** [getnikola/nikola-netlify-cms#17]
I tried to build a site with this repo and got the following error when I added ipynb files.

![r0052390](https://user-images.githubusercontent.com/31384629/87235201-60682d80-c3f7-11ea-97da-115902d0b64f.png)

I added **notebook==6.0.3** to **requirements.txt** and it worked fine.

My question (or suggestion) is whether "notebook==6.0.3" be added to requirements by default? My personal opinion is yes, because:
1. Not many are tech savvy or have time/resources to figure out what needs to be done to publish ipynb files.
2. In my opinion, one of the main USPs of Nikola compared to other SSGs is it's ability to publish Jupyter notebooks without users having to convert them to markdown. Why not extend the same convenience when using Netlify or GitLab? I raised the same issue there in Gitlab but having got no response, I had to create a new docker image for Nikola as the existing one fails. I am personally happy with it because, in the process, I learned yaml and building docker images. But I don't think many end users are like that. Most follow documentation, and if it works then fine, else raise an issue and when it doesn't get addressed, they move on elsewhere. I believe that little fixes like these could create a big impact on users by making things easier for them. I really like Nikola and so far, it's the best SSG for me. I want others to feel that way too.

However, if you feel that "notebook==6.0.3" should not be added to requirements by default, could you please mention in *Readme* that users add this requirement while publishing Jupyter notebooks?

**Comment by Kwpolska** [comment]
I changed the requirements to `Nikola[extras]`, we do that for the GitHub action already. This does take in more packages, but users can still change it back, and it shouldn’t extend install times by much. But I think you are overstating the importance of Jupyter, Nikola has many other features people might be interested in.

**Comment by k-allika** [comment]
Thank you for updating requrements.

I may be overstating the importance of Jupyter because I personally am more interested in publishing Jupyter notebooks. Most data scientists like me work with Jupyter notebooks (for both python and r) and some would like to publish their work online. Earlier, I had to convert notebooks to html and publish them, which is a bit of a hassle when it comes to formatting and images. Now, I find Nikola very convenient. I couldn't find any other SSG  that does that (Jekyll, Pelican, etc require me to convert files to .md first). May be people like me amount to a very small proportion in Nikola user base, yet, this feature is a huge benefit to me. 

I am still new to Nikola (or even publishing websites for that matter). As I explore, I keep finding interesting features. 

It's probably not very wise to write so much on an issues page. 

Thanks for your time and for all the work that goes into this project. Cheers.
