### ISSUE TITLE
Python 3.6 runtime not available anymore

### ISSUE THREAD

**Issue by uyar** [getnikola/nikola-netlify-cms#6]
If I'm not mistaken, the Python 3.6 runtime is no longer available on Netlify and the deployment fails. The runtime.txt file should be updated.

As a side note, I don't know how important this is, but the requirements file lists the Nikola dependency as version 8.0.1. As of this writing the current version is 8.0.4. Other pinned dependencies can also be outdated.

**Comment by Kwpolska** [comment]
Thanks, I updated the versions.
