### ISSUE TITLE
Explicitly matching frontmatter formats

### ISSUE THREAD

**Issue by uyar** [getnikola/nikola-netlify-cms#7]
Wouldn't it be better to explicitly match the frontmatter format used by both Nikola and Netlify CMS? At the moment, these are unset on both sides. Setting METADATA_FORMAT to "YAML" in Nikola conf.py and "format: yaml-frontmatter" in files/admin/config.yml for both posts and pages would be safer, in my opinion.

When that is done, the "tags" field could also be set to use the "list" widget instead of the "string" widget. And I think that the "text" widget might be better suited for the "description" field.

**Comment by Kwpolska** [comment]
> When that is done, the "tags" field could also be set to use the "list" widget instead of the "string" widget. And I think that the "text" widget might be better suited for the "description" field.

 :+1: on tags, but descriptions are expected to be one-line strings in general, so a multi-line input field is not necessary.
