### ISSUE TITLE
Missing frontmatter fields in config.yml

### ISSUE THREAD

**Issue by uyar** [getnikola/nikola-netlify-cms#8]
Some frontmatter data listed in the Nikola documentation are not available through the Netlify CMS editor due to being missing from the config.yml file. They are: hidetitle, updated, author, status, link, template, type, pretty_url, nocomments, hyphenate, has_math. Some of these might not be needed for a general audience but some (for example author) could be included.

**Comment by Kwpolska** [comment]
We should not add too many. Here’s an opinionated list:

Definitely: author, updated
Maybe: status, has_math, nocomments, type, link
No: hidetitle, template, pretty_url, hyphenate (those are pretty specialized)

For the “maybe” list, add only as many as can reasonably fit on the page.
